### ISSUE TITLE
Nagios- Tekla Server Moved to VM with IP chan from 192.168.25.20 to 23

### ISSUE THREAD

**Issue by bhupender-isgec** [Isgec/ITIL-NAGIOS#2]
Tekla Server monitoring issue under nagios. Server is up but nagios showing down.

**Comment by bhupender-isgec** [comment]
Server is moved fron 192.168.25.23 to 192.168.25.20 on VM. it was monitored under nagios with IP 192.168.25.23 hence IP change required & done.

![image](https://user-images.githubusercontent.com/49862746/103848159-c47a5e80-50c7-11eb-9277-16364dd48a40.png)

**Comment by hariharan-isgec** [comment]
@Isgec/dc-infra-team update any further actions on this issue

**Comment by hariharan-isgec** [comment]
@dhirendra-isgec Issue resolved, please close
